// Моковые данные для системы стажировок

import type {
  Internship,
  InternshipApplication,
  InternshipStudent,
  Mentor,
  InternshipSettings,
} from '@/types/internships';

// Настройки по умолчанию
export const defaultInternshipSettings: InternshipSettings = {
  maxApplicationsPerStudent: 3,
  autoCloseOnLimit: true,
  requireReserveList: true,
  reserveListSize: 20, // 20% от основных мест
  minMatchScore: 60,
  approvalWorkflow: 'two-level',
  requireInterview: false,
  autoNotifyOnStatusChange: true,
  balanceByUniversity: false,
};

// Моковые наставники
export const mockMentors: Mentor[] = [
  {
    id: 'mentor-1',
    fullName: 'Иванов Петр Сергеевич',
    email: 'p.ivanov@example.com',
    position: 'Ведущий разработчик',
    departmentId: 'dept-2',
    departmentName: 'Управление развития общекорпоративных систем',
    skills: ['skill-1', 'skill-2', 'skill-3'],
    maxInternships: 3,
    currentInternships: 1,
  },
  {
    id: 'mentor-2',
    fullName: 'Сидорова Мария Александровна',
    email: 'm.sidorova@example.com',
    position: 'Старший разработчик',
    departmentId: 'dept-3',
    departmentName: 'Управление разработки банковских продуктов',
    skills: ['skill-2', 'skill-4', 'skill-5'],
    maxInternships: 2,
    currentInternships: 0,
  },
];

// Моковые студенты
export const mockStudents: InternshipStudent[] = [
  {
    id: 'student-1',
    fullName: 'Петров Алексей Дмитриевич',
    email: 'a.petrov@university1.edu',
    phone: '+7 (999) 123-45-67',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 3,
    group: 'ИТ-3-21',
    specialization: 'Программная инженерия',
    gpa: 4.5,
    skills: ['skill-1', 'skill-2', 'skill-3'],
    experience: {
      projects: ['Веб-приложение для управления задачами', 'Мобильное приложение на React Native'],
      workExperience: ['Стажировка в IT-компании (3 месяца)'],
      achievements: ['Победитель хакатона 2023'],
    },
  },
  {
    id: 'student-2',
    fullName: 'Козлова Анна Сергеевна',
    email: 'a.kozlova@university1.edu',
    phone: '+7 (999) 234-56-78',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 4,
    group: 'ИТ-4-20',
    specialization: 'Информационные системы',
    gpa: 4.8,
    skills: ['skill-2', 'skill-4', 'skill-5'],
    experience: {
      projects: ['Система аналитики данных', 'Корпоративный портал'],
      workExperience: ['Разработчик в стартапе (6 месяцев)'],
      achievements: ['Стипендиат президента', 'Публикация в научном журнале'],
    },
  },
  {
    id: 'student-3',
    fullName: 'Смирнов Дмитрий Игоревич',
    email: 'd.smirnov@university2.edu',
    phone: '+7 (999) 345-67-89',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 3,
    group: 'ПИ-3-21',
    specialization: 'Прикладная информатика',
    gpa: 4.2,
    skills: ['skill-1', 'skill-3', 'skill-6'],
    experience: {
      projects: ['Игра на Unity', 'Чат-бот для Telegram'],
      workExperience: [],
      achievements: [],
    },
  },
  {
    id: 'student-4',
    fullName: 'Волкова Елена Петровна',
    email: 'e.volkova@university2.edu',
    phone: '+7 (999) 456-78-90',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 4,
    group: 'ПИ-4-20',
    specialization: 'Программная инженерия',
    gpa: 4.7,
    skills: ['skill-2', 'skill-4', 'skill-5', 'skill-7'],
    experience: {
      projects: ['E-commerce платформа', 'Система управления проектами'],
      workExperience: ['Frontend разработчик (1 год)'],
      achievements: ['Призер олимпиады по программированию'],
    },
  },
  {
    id: 'student-5',
    fullName: 'Новиков Игорь Владимирович',
    email: 'i.novikov@university3.edu',
    phone: '+7 (999) 567-89-01',
    universityId: 'univ-3',
    universityName: 'Новосибирский государственный университет',
    course: 2,
    group: 'ИТ-2-22',
    specialization: 'Информатика и вычислительная техника',
    gpa: 4.0,
    skills: ['skill-1', 'skill-2'],
    experience: {
      projects: ['Личный сайт-портфолио'],
      workExperience: [],
      achievements: [],
    },
  },
];

// Моковые стажировки
export const mockInternships: Internship[] = [
  {
    id: 'internship-1',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Frontend разработка на React',
    description: 'Стажировка для студентов, интересующихся современной веб-разработкой. Работа над реальными проектами под руководством опытных наставников.',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-08-31'),
    applicationDeadline: new Date('2024-06-15'),
    status: 'recruiting',
    maxParticipants: 10,
    currentParticipants: 0,
    requirements: [
      'Знание JavaScript и TypeScript',
      'Опыт работы с React',
      'Понимание основ HTML/CSS',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-1', 'skill-2'],
    preferredSkills: ['skill-3', 'skill-4'],
    mentorId: 'mentor-1',
    mentorName: 'Иванов Петр Сергеевич',
    location: 'hybrid',
    city: 'Москва',
    address: 'ул. Ленина, д. 1',
    salary: 30000,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-15'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-2',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Backend разработка на Node.js',
    description: 'Изучение серверной разработки, работа с базами данных, создание REST API.',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-08-31'),
    applicationDeadline: new Date('2024-06-15'),
    status: 'recruiting',
    maxParticipants: 8,
    currentParticipants: 0,
    requirements: [
      'Знание JavaScript/TypeScript',
      'Понимание основ баз данных',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-2', 'skill-5'],
    preferredSkills: ['skill-6'],
    mentorId: 'mentor-2',
    mentorName: 'Сидорова Мария Александровна',
    location: 'remote',
    salary: 25000,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-15'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-3',
    partnershipId: 'partnership-2',
    partnershipName: 'Осенняя стажировка 2024',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    title: 'Мобильная разработка',
    description: 'Разработка мобильных приложений для iOS и Android.',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2024-11-30'),
    applicationDeadline: new Date('2024-08-15'),
    status: 'planned',
    maxParticipants: 12,
    currentParticipants: 0,
    requirements: [
      'Знание Swift/Kotlin или React Native',
      'Опыт разработки мобильных приложений',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-7'],
    preferredSkills: ['skill-1', 'skill-2'],
    location: 'office',
    city: 'Санкт-Петербург',
    address: 'Невский проспект, д. 28',
    salary: 35000,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-4',
    partnershipId: 'partnership-3',
    partnershipName: 'Весенняя стажировка 2024',
    universityId: 'univ-3',
    universityName: 'Московский физико-технический институт',
    title: 'Data Science и машинное обучение',
    description: 'Работа с большими данными, построение моделей машинного обучения, анализ данных.',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-05-31'),
    applicationDeadline: new Date('2024-02-15'),
    status: 'active',
    maxParticipants: 15,
    currentParticipants: 12,
    requirements: [
      'Знание Python',
      'Опыт работы с pandas, numpy',
      'Понимание основ ML',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-5', 'skill-6'],
    preferredSkills: ['skill-1'],
    mentorId: 'mentor-1',
    mentorName: 'Иванов Петр Сергеевич',
    location: 'hybrid',
    city: 'Москва',
    address: 'ул. Мира, д. 5',
    salary: 40000,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-28'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-5',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'DevOps и облачные технологии',
    description: 'Изучение CI/CD, Docker, Kubernetes, работа с облачными платформами.',
    startDate: new Date('2024-06-15'),
    endDate: new Date('2024-08-15'),
    applicationDeadline: new Date('2024-05-30'),
    status: 'recruiting',
    maxParticipants: 8,
    currentParticipants: 3,
    requirements: [
      'Базовые знания Linux',
      'Понимание основ DevOps',
      'Курс 2-4',
    ],
    requiredSkills: ['skill-2'],
    preferredSkills: ['skill-5'],
    location: 'remote',
    salary: 28000,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-05-20'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-6',
    partnershipId: 'partnership-2',
    partnershipName: 'Осенняя стажировка 2024',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    title: 'Fullstack разработка',
    description: 'Полный цикл разработки веб-приложений: от frontend до backend и баз данных.',
    startDate: new Date('2024-09-15'),
    endDate: new Date('2024-12-15'),
    applicationDeadline: new Date('2024-08-30'),
    status: 'planned',
    maxParticipants: 10,
    currentParticipants: 0,
    requirements: [
      'Знание JavaScript/TypeScript',
      'Опыт с React или Vue',
      'Базовые знания Node.js',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-1', 'skill-2'],
    preferredSkills: ['skill-4', 'skill-5'],
    mentorId: 'mentor-2',
    mentorName: 'Сидорова Мария Александровна',
    location: 'office',
    city: 'Санкт-Петербург',
    address: 'ул. Литейная, д. 42',
    salary: 32000,
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-07-01'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-7',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'QA и тестирование',
    description: 'Изучение различных видов тестирования, автоматизация тестов, работа с тестовыми фреймворками.',
    startDate: new Date('2024-07-10'),
    endDate: new Date('2024-09-10'),
    applicationDeadline: new Date('2024-06-25'),
    status: 'active',
    maxParticipants: 12,
    currentParticipants: 8,
    requirements: [
      'Понимание основ тестирования',
      'Внимательность к деталям',
      'Курс 2-4',
    ],
    requiredSkills: ['skill-2'],
    preferredSkills: ['skill-1'],
    location: 'hybrid',
    city: 'Москва',
    address: 'ул. Тверская, д. 10',
    salary: 27000,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-07-09'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-8',
    partnershipId: 'partnership-3',
    partnershipName: 'Весенняя стажировка 2024',
    universityId: 'univ-3',
    universityName: 'Московский физико-технический институт',
    title: 'Кибербезопасность',
    description: 'Изучение основ информационной безопасности, анализ уязвимостей, защита данных.',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-04-30'),
    applicationDeadline: new Date('2024-01-15'),
    status: 'completed',
    maxParticipants: 6,
    currentParticipants: 6,
    requirements: [
      'Знание основ сетей',
      'Понимание основ безопасности',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-5'],
    preferredSkills: ['skill-6'],
    mentorId: 'mentor-1',
    mentorName: 'Иванов Петр Сергеевич',
    location: 'office',
    city: 'Москва',
    address: 'пр-т Вернадского, д. 78',
    salary: 38000,
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-04-30'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-9',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'UI/UX дизайн',
    description: 'Создание пользовательских интерфейсов, работа с Figma, проектирование пользовательского опыта.',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-07-31'),
    applicationDeadline: new Date('2024-05-15'),
    status: 'recruiting',
    maxParticipants: 10,
    currentParticipants: 5,
    requirements: [
      'Навыки дизайна',
      'Знание Figma или Adobe XD',
      'Понимание UX принципов',
      'Курс 2-4',
    ],
    requiredSkills: ['skill-4'],
    preferredSkills: ['skill-1'],
    location: 'remote',
    salary: 26000,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-05-20'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-10',
    partnershipId: 'partnership-2',
    partnershipName: 'Осенняя стажировка 2024',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    title: 'Blockchain разработка',
    description: 'Изучение технологии блокчейн, разработка смарт-контрактов, работа с криптовалютами.',
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-12-31'),
    applicationDeadline: new Date('2024-09-15'),
    status: 'planned',
    maxParticipants: 8,
    currentParticipants: 0,
    requirements: [
      'Знание JavaScript или Python',
      'Понимание основ криптографии',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-2'],
    preferredSkills: ['skill-5'],
    location: 'hybrid',
    city: 'Санкт-Петербург',
    address: 'ул. Некрасова, д. 15',
    salary: 45000,
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-01'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-11',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Backend на Python',
    description: 'Разработка серверной части приложений на Python, работа с Django и Flask.',
    startDate: new Date('2024-07-05'),
    endDate: new Date('2024-08-30'),
    applicationDeadline: new Date('2024-06-20'),
    status: 'active',
    maxParticipants: 10,
    currentParticipants: 9,
    requirements: [
      'Знание Python',
      'Понимание REST API',
      'Базовые знания баз данных',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-5'],
    preferredSkills: ['skill-6'],
    mentorId: 'mentor-2',
    mentorName: 'Сидорова Мария Александровна',
    location: 'office',
    city: 'Москва',
    address: 'ул. Арбат, д. 25',
    salary: 33000,
    createdAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-07-04'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-12',
    partnershipId: 'partnership-3',
    partnershipName: 'Весенняя стажировка 2024',
    universityId: 'univ-3',
    universityName: 'Московский физико-технический институт',
    title: 'Игровая разработка',
    description: 'Создание игр на Unity или Unreal Engine, работа с игровыми движками.',
    startDate: new Date('2024-03-15'),
    endDate: new Date('2024-06-15'),
    applicationDeadline: new Date('2024-02-28'),
    status: 'completed',
    maxParticipants: 15,
    currentParticipants: 15,
    requirements: [
      'Знание C# или C++',
      'Опыт работы с Unity/Unreal',
      'Курс 2-4',
    ],
    requiredSkills: ['skill-7'],
    preferredSkills: ['skill-1', 'skill-2'],
    location: 'office',
    city: 'Москва',
    address: 'ул. Садовая, д. 7',
    salary: 36000,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-06-15'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-13',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Системное программирование',
    description: 'Разработка системного ПО, работа с низкоуровневыми технологиями, оптимизация производительности.',
    startDate: new Date('2024-08-01'),
    endDate: new Date('2024-09-30'),
    applicationDeadline: new Date('2024-07-15'),
    status: 'recruiting',
    maxParticipants: 6,
    currentParticipants: 2,
    requirements: [
      'Знание C/C++',
      'Понимание архитектуры компьютера',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-5'],
    preferredSkills: ['skill-6'],
    location: 'hybrid',
    city: 'Москва',
    address: 'ул. Ломоносова, д. 12',
    salary: 42000,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-07-10'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-14',
    partnershipId: 'partnership-2',
    partnershipName: 'Осенняя стажировка 2024',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    title: 'Frontend на Vue.js',
    description: 'Разработка современных веб-интерфейсов с использованием Vue.js и композиционного API.',
    startDate: new Date('2024-09-20'),
    endDate: new Date('2024-11-20'),
    applicationDeadline: new Date('2024-09-05'),
    status: 'planned',
    maxParticipants: 10,
    currentParticipants: 0,
    requirements: [
      'Знание JavaScript/TypeScript',
      'Опыт работы с Vue.js',
      'Понимание компонентной архитектуры',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-1', 'skill-2'],
    preferredSkills: ['skill-3'],
    mentorId: 'mentor-1',
    mentorName: 'Иванов Петр Сергеевич',
    location: 'remote',
    salary: 29000,
    createdAt: new Date('2024-08-10'),
    updatedAt: new Date('2024-08-10'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-15',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Аналитика данных',
    description: 'Работа с данными, создание дашбордов, анализ бизнес-метрик, визуализация.',
    startDate: new Date('2024-07-15'),
    endDate: new Date('2024-09-15'),
    applicationDeadline: new Date('2024-06-30'),
    status: 'active',
    maxParticipants: 12,
    currentParticipants: 10,
    requirements: [
      'Знание SQL',
      'Опыт работы с Excel или Python',
      'Аналитическое мышление',
      'Курс 2-4',
    ],
    requiredSkills: ['skill-5'],
    preferredSkills: ['skill-6'],
    location: 'office',
    city: 'Москва',
    address: 'ул. Пушкина, д. 18',
    salary: 31000,
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-07-14'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-16',
    partnershipId: 'partnership-3',
    partnershipName: 'Весенняя стажировка 2024',
    universityId: 'univ-3',
    universityName: 'Московский физико-технический институт',
    title: 'Embedded системы',
    description: 'Программирование микроконтроллеров, работа с Arduino, разработка IoT решений.',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2024-06-30'),
    applicationDeadline: new Date('2024-03-15'),
    status: 'completed',
    maxParticipants: 8,
    currentParticipants: 8,
    requirements: [
      'Знание C/C++',
      'Понимание основ электроники',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-5', 'skill-6'],
    preferredSkills: ['skill-7'],
    mentorId: 'mentor-2',
    mentorName: 'Сидорова Мария Александровна',
    location: 'office',
    city: 'Москва',
    address: 'пр-т Мира, д. 95',
    salary: 37000,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-30'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-17',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Product Management',
    description: 'Управление продуктом, работа с требованиями, планирование, взаимодействие с командой разработки.',
    startDate: new Date('2024-08-10'),
    endDate: new Date('2024-10-10'),
    applicationDeadline: new Date('2024-07-25'),
    status: 'recruiting',
    maxParticipants: 5,
    currentParticipants: 1,
    requirements: [
      'Аналитическое мышление',
      'Коммуникативные навыки',
      'Понимание IT процессов',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-4'],
    preferredSkills: ['skill-1'],
    location: 'hybrid',
    city: 'Москва',
    address: 'ул. Красная Площадь, д. 1',
    salary: 35000,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-07-20'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-18',
    partnershipId: 'partnership-2',
    partnershipName: 'Осенняя стажировка 2024',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    title: 'React Native разработка',
    description: 'Создание кроссплатформенных мобильных приложений с использованием React Native.',
    startDate: new Date('2024-10-15'),
    endDate: new Date('2024-12-15'),
    applicationDeadline: new Date('2024-09-30'),
    status: 'planned',
    maxParticipants: 10,
    currentParticipants: 0,
    requirements: [
      'Знание React',
      'Опыт работы с JavaScript',
      'Понимание мобильной разработки',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-1', 'skill-7'],
    preferredSkills: ['skill-2'],
    location: 'remote',
    salary: 34000,
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date('2024-08-20'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-19',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Архитектура ПО',
    description: 'Изучение принципов проектирования архитектуры приложений, паттернов проектирования, масштабируемости.',
    startDate: new Date('2024-07-20'),
    endDate: new Date('2024-09-20'),
    applicationDeadline: new Date('2024-07-05'),
    status: 'cancelled',
    maxParticipants: 8,
    currentParticipants: 0,
    requirements: [
      'Опыт разработки от 1 года',
      'Знание паттернов проектирования',
      'Курс 4',
    ],
    requiredSkills: ['skill-2', 'skill-5'],
    preferredSkills: ['skill-6'],
    mentorId: 'mentor-1',
    mentorName: 'Иванов Петр Сергеевич',
    location: 'office',
    city: 'Москва',
    address: 'ул. Варшавское шоссе, д. 47',
    salary: 41000,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-07-15'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-20',
    partnershipId: 'partnership-2',
    partnershipName: 'Осенняя стажировка 2024',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    title: 'Микросервисная архитектура',
    description: 'Разработка распределенных систем, работа с микросервисами, Docker, Kubernetes.',
    startDate: new Date('2024-11-01'),
    endDate: new Date('2025-01-31'),
    applicationDeadline: new Date('2024-10-15'),
    status: 'planned',
    maxParticipants: 10,
    currentParticipants: 0,
    requirements: [
      'Знание Docker и Kubernetes',
      'Опыт работы с микросервисами',
      'Понимание распределенных систем',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-2', 'skill-5'],
    preferredSkills: ['skill-6'],
    mentorId: 'mentor-2',
    mentorName: 'Сидорова Мария Александровна',
    location: 'hybrid',
    city: 'Санкт-Петербург',
    address: 'Невский проспект, д. 50',
    salary: 43000,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
    createdBy: 'user-1',
  },
];

// Моковые заявки
export const mockApplications: InternshipApplication[] = [
  {
    id: 'app-1',
    internshipId: 'internship-1',
    studentId: 'student-1',
    studentName: 'Петров Алексей Дмитриевич',
    studentEmail: 'a.petrov@university1.edu',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 3,
    gpa: 4.5,
    status: 'approved',
    appliedAt: new Date('2024-05-10'),
    reviewedAt: new Date('2024-05-12'),
    reviewerId: 'user-1',
    reviewerName: 'HR Менеджер',
    motivationLetter: 'Очень хочу получить опыт работы в крупной компании...',
    matchScore: 85,
    matchFactors: {
      skillsMatch: 90,
      experience: 80,
      gpa: 90,
      motivationQuality: 75,
    },
    isReserve: false,
  },
  {
    id: 'app-2',
    internshipId: 'internship-1',
    studentId: 'student-2',
    studentName: 'Козлова Анна Сергеевна',
    studentEmail: 'a.kozlova@university1.edu',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 4,
    gpa: 4.8,
    status: 'pending',
    appliedAt: new Date('2024-05-14'),
    matchScore: 92,
    matchFactors: {
      skillsMatch: 95,
      experience: 90,
      gpa: 96,
      motivationQuality: 85,
    },
    isReserve: false,
  },
  {
    id: 'app-3',
    internshipId: 'internship-1',
    studentId: 'student-3',
    studentName: 'Смирнов Дмитрий Игоревич',
    studentEmail: 'd.smirnov@university2.edu',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 3,
    gpa: 4.2,
    status: 'rejected',
    appliedAt: new Date('2024-05-08'),
    reviewedAt: new Date('2024-05-11'),
    reviewerId: 'user-1',
    reviewerName: 'HR Менеджер',
    rejectionReason: 'Недостаточный опыт работы с React',
    matchScore: 55,
    matchFactors: {
      skillsMatch: 50,
      experience: 40,
      gpa: 84,
    },
    isReserve: false,
  },
  {
    id: 'app-4',
    internshipId: 'internship-2',
    studentId: 'student-4',
    studentName: 'Волкова Елена Петровна',
    studentEmail: 'e.volkova@university2.edu',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 4,
    gpa: 4.7,
    status: 'confirmed',
    appliedAt: new Date('2024-05-09'),
    reviewedAt: new Date('2024-05-13'),
    reviewerId: 'user-1',
    reviewerName: 'HR Менеджер',
    confirmedAt: new Date('2024-05-15'),
    matchScore: 88,
    matchFactors: {
      skillsMatch: 90,
      experience: 85,
      gpa: 94,
      motivationQuality: 80,
    },
    isReserve: false,
  },
];
