// Моковые данные для системы стажировок

import type {
  Internship,
  InternshipApplication,
  InternshipStudent,
  Mentor,
  InternshipSettings,
} from '@/types/internships';

// Настройки по умолчанию
export const defaultInternshipSettings: InternshipSettings = {
  maxApplicationsPerStudent: 3,
  autoCloseOnLimit: true,
  requireReserveList: true,
  reserveListSize: 20, // 20% от основных мест
  minMatchScore: 60,
  approvalWorkflow: 'two-level',
  requireInterview: false,
  autoNotifyOnStatusChange: true,
  balanceByUniversity: false,
};

// Моковые наставники
export const mockMentors: Mentor[] = [
  {
    id: 'mentor-1',
    fullName: 'Иванов Петр Сергеевич',
    email: 'p.ivanov@example.com',
    position: 'Ведущий разработчик',
    departmentId: 'dept-2',
    departmentName: 'Управление развития общекорпоративных систем',
    skills: ['skill-1', 'skill-2', 'skill-3'],
    maxInternships: 3,
    currentInternships: 1,
  },
  {
    id: 'mentor-2',
    fullName: 'Сидорова Мария Александровна',
    email: 'm.sidorova@example.com',
    position: 'Старший разработчик',
    departmentId: 'dept-3',
    departmentName: 'Управление разработки банковских продуктов',
    skills: ['skill-2', 'skill-4', 'skill-5'],
    maxInternships: 2,
    currentInternships: 0,
  },
];

// Моковые студенты
export const mockStudents: InternshipStudent[] = [
  {
    id: 'student-1',
    fullName: 'Петров Алексей Дмитриевич',
    email: 'a.petrov@university1.edu',
    phone: '+7 (999) 123-45-67',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 3,
    group: 'ИТ-3-21',
    specialization: 'Программная инженерия',
    gpa: 4.5,
    skills: ['skill-1', 'skill-2', 'skill-3'],
    experience: {
      projects: ['Веб-приложение для управления задачами', 'Мобильное приложение на React Native'],
      workExperience: ['Стажировка в IT-компании (3 месяца)'],
      achievements: ['Победитель хакатона 2023'],
    },
  },
  {
    id: 'student-2',
    fullName: 'Козлова Анна Сергеевна',
    email: 'a.kozlova@university1.edu',
    phone: '+7 (999) 234-56-78',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 4,
    group: 'ИТ-4-20',
    specialization: 'Информационные системы',
    gpa: 4.8,
    skills: ['skill-2', 'skill-4', 'skill-5'],
    experience: {
      projects: ['Система аналитики данных', 'Корпоративный портал'],
      workExperience: ['Разработчик в стартапе (6 месяцев)'],
      achievements: ['Стипендиат президента', 'Публикация в научном журнале'],
    },
  },
  {
    id: 'student-3',
    fullName: 'Смирнов Дмитрий Игоревич',
    email: 'd.smirnov@university2.edu',
    phone: '+7 (999) 345-67-89',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 3,
    group: 'ПИ-3-21',
    specialization: 'Прикладная информатика',
    gpa: 4.2,
    skills: ['skill-1', 'skill-3', 'skill-6'],
    experience: {
      projects: ['Игра на Unity', 'Чат-бот для Telegram'],
      workExperience: [],
      achievements: [],
    },
  },
  {
    id: 'student-4',
    fullName: 'Волкова Елена Петровна',
    email: 'e.volkova@university2.edu',
    phone: '+7 (999) 456-78-90',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 4,
    group: 'ПИ-4-20',
    specialization: 'Программная инженерия',
    gpa: 4.7,
    skills: ['skill-2', 'skill-4', 'skill-5', 'skill-7'],
    experience: {
      projects: ['E-commerce платформа', 'Система управления проектами'],
      workExperience: ['Frontend разработчик (1 год)'],
      achievements: ['Призер олимпиады по программированию'],
    },
  },
  {
    id: 'student-5',
    fullName: 'Новиков Игорь Владимирович',
    email: 'i.novikov@university3.edu',
    phone: '+7 (999) 567-89-01',
    universityId: 'univ-3',
    universityName: 'Новосибирский государственный университет',
    course: 2,
    group: 'ИТ-2-22',
    specialization: 'Информатика и вычислительная техника',
    gpa: 4.0,
    skills: ['skill-1', 'skill-2'],
    experience: {
      projects: ['Личный сайт-портфолио'],
      workExperience: [],
      achievements: [],
    },
  },
];

// Моковые стажировки
export const mockInternships: Internship[] = [
  {
    id: 'internship-1',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Frontend разработка на React',
    description: 'Стажировка для студентов, интересующихся современной веб-разработкой. Работа над реальными проектами под руководством опытных наставников.',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-08-31'),
    applicationDeadline: new Date('2024-06-15'),
    status: 'recruiting',
    maxParticipants: 10,
    currentParticipants: 0,
    requirements: [
      'Знание JavaScript и TypeScript',
      'Опыт работы с React',
      'Понимание основ HTML/CSS',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-1', 'skill-2'],
    preferredSkills: ['skill-3', 'skill-4'],
    mentorId: 'mentor-1',
    mentorName: 'Иванов Петр Сергеевич',
    location: 'hybrid',
    city: 'Москва',
    address: 'ул. Ленина, д. 1',
    salary: 30000,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-15'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-2',
    partnershipId: 'partnership-1',
    partnershipName: 'Летняя стажировка 2024',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    title: 'Backend разработка на Node.js',
    description: 'Изучение серверной разработки, работа с базами данных, создание REST API.',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-08-31'),
    applicationDeadline: new Date('2024-06-15'),
    status: 'recruiting',
    maxParticipants: 8,
    currentParticipants: 0,
    requirements: [
      'Знание JavaScript/TypeScript',
      'Понимание основ баз данных',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-2', 'skill-5'],
    preferredSkills: ['skill-6'],
    mentorId: 'mentor-2',
    mentorName: 'Сидорова Мария Александровна',
    location: 'remote',
    salary: 25000,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-15'),
    createdBy: 'user-1',
  },
  {
    id: 'internship-3',
    partnershipId: 'partnership-2',
    partnershipName: 'Осенняя стажировка 2024',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    title: 'Мобильная разработка',
    description: 'Разработка мобильных приложений для iOS и Android.',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2024-11-30'),
    applicationDeadline: new Date('2024-08-15'),
    status: 'planned',
    maxParticipants: 12,
    currentParticipants: 0,
    requirements: [
      'Знание Swift/Kotlin или React Native',
      'Опыт разработки мобильных приложений',
      'Курс 3-4',
    ],
    requiredSkills: ['skill-7'],
    preferredSkills: ['skill-1', 'skill-2'],
    location: 'office',
    city: 'Санкт-Петербург',
    address: 'Невский проспект, д. 28',
    salary: 35000,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
    createdBy: 'user-1',
  },
];

// Моковые заявки
export const mockApplications: InternshipApplication[] = [
  {
    id: 'app-1',
    internshipId: 'internship-1',
    studentId: 'student-1',
    studentName: 'Петров Алексей Дмитриевич',
    studentEmail: 'a.petrov@university1.edu',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 3,
    gpa: 4.5,
    status: 'approved',
    appliedAt: new Date('2024-05-10'),
    reviewedAt: new Date('2024-05-12'),
    reviewerId: 'user-1',
    reviewerName: 'HR Менеджер',
    motivationLetter: 'Очень хочу получить опыт работы в крупной компании...',
    matchScore: 85,
    matchFactors: {
      skillsMatch: 90,
      experience: 80,
      gpa: 90,
      motivationQuality: 75,
    },
    isReserve: false,
  },
  {
    id: 'app-2',
    internshipId: 'internship-1',
    studentId: 'student-2',
    studentName: 'Козлова Анна Сергеевна',
    studentEmail: 'a.kozlova@university1.edu',
    universityId: 'univ-1',
    universityName: 'Московский государственный университет',
    course: 4,
    gpa: 4.8,
    status: 'pending',
    appliedAt: new Date('2024-05-14'),
    matchScore: 92,
    matchFactors: {
      skillsMatch: 95,
      experience: 90,
      gpa: 96,
      motivationQuality: 85,
    },
    isReserve: false,
  },
  {
    id: 'app-3',
    internshipId: 'internship-1',
    studentId: 'student-3',
    studentName: 'Смирнов Дмитрий Игоревич',
    studentEmail: 'd.smirnov@university2.edu',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 3,
    gpa: 4.2,
    status: 'rejected',
    appliedAt: new Date('2024-05-08'),
    reviewedAt: new Date('2024-05-11'),
    reviewerId: 'user-1',
    reviewerName: 'HR Менеджер',
    rejectionReason: 'Недостаточный опыт работы с React',
    matchScore: 55,
    matchFactors: {
      skillsMatch: 50,
      experience: 40,
      gpa: 84,
    },
    isReserve: false,
  },
  {
    id: 'app-4',
    internshipId: 'internship-2',
    studentId: 'student-4',
    studentName: 'Волкова Елена Петровна',
    studentEmail: 'e.volkova@university2.edu',
    universityId: 'univ-2',
    universityName: 'Санкт-Петербургский государственный университет',
    course: 4,
    gpa: 4.7,
    status: 'confirmed',
    appliedAt: new Date('2024-05-09'),
    reviewedAt: new Date('2024-05-13'),
    reviewerId: 'user-1',
    reviewerName: 'HR Менеджер',
    confirmedAt: new Date('2024-05-15'),
    matchScore: 88,
    matchFactors: {
      skillsMatch: 90,
      experience: 85,
      gpa: 94,
      motivationQuality: 80,
    },
    isReserve: false,
  },
];
