import type {
  OrgUnit,
  Report,
  ReportUser,
  VisibilityPolicy,
} from "./types";

export const users: ReportUser[] = [
  {
    id: "u-employee",
    fullName: "Сотрудник отдела оценки персонала",
    role: "EMPLOYEE",
    unitId: "unit-assessment",
    managerId: "u-head-section",
  },
  {
    id: "u-head-section",
    fullName: "Начальник отдела",
    role: "HEAD_OF_SECTION",
    unitId: "unit-assessment",
    managerId: "u-head-directorate",
  },
  {
    id: "u-head-directorate",
    fullName: "Начальник управления",
    role: "HEAD_OF_DIRECTORATE",
    unitId: "unit-directorate",
    managerId: "u-deputy-department-head",
  },
  {
    id: "u-deputy-department-head",
    fullName: "Заместитель начальника департамента",
    role: "DEPUTY_DEPARTMENT_HEAD",
    unitId: "unit-department",
    managerId: "u-department-head",
  },
  {
    id: "u-department-head",
    fullName: "Начальник департамента",
    role: "DEPARTMENT_HEAD",
    unitId: "unit-department",
    managerId: "u-executive",
  },
  {
    id: "u-executive",
    fullName: "Курирующее ВДЛ",
    role: "EXECUTIVE",
    unitId: "unit-company",
    managerId: null,
  },
  {
    id: "u-customer",
    fullName: "Заказчик исследования",
    role: "HEAD_OF_DIRECTORATE",
    unitId: "unit-directorate",
    managerId: "u-deputy-department-head",
    isResearchCustomer: true,
  },
];

export const orgUnits: OrgUnit[] = [
  {
    id: "unit-company",
    name: "Компания",
    parentUnitId: null,
    managerUserId: "u-executive",
  },
  {
    id: "unit-department",
    name: "Департамент",
    parentUnitId: "unit-company",
    managerUserId: "u-department-head",
  },
  {
    id: "unit-directorate",
    name: "Управление",
    parentUnitId: "unit-department",
    managerUserId: "u-head-directorate",
  },
  {
    id: "unit-assessment",
    name: "Отдел оценки персонала",
    parentUnitId: "unit-directorate",
    managerUserId: "u-head-section",
  },
];

export const defaultPolicies: VisibilityPolicy[] = [
  {
    reportType: "INDIVIDUAL",
    allowSelfOwner: true,
    allowOwnerManagerChain: true,
    allowUnitManagerHierarchy: false,
    minimumRoleRankForUnitHierarchy: 1,
    allowResearchCustomers: false,
    additionalViewerRoleRanks: [],
  },
  {
    reportType: "GROUP",
    allowSelfOwner: false,
    allowOwnerManagerChain: false,
    allowUnitManagerHierarchy: true,
    minimumRoleRankForUnitHierarchy: 2,
    allowResearchCustomers: false,
    additionalViewerRoleRanks: [],
  },
  {
    reportType: "SUMMARY",
    allowSelfOwner: false,
    allowOwnerManagerChain: false,
    allowUnitManagerHierarchy: true,
    minimumRoleRankForUnitHierarchy: 3,
    allowResearchCustomers: false,
    additionalViewerRoleRanks: [],
  },
  {
    reportType: "OVERALL",
    allowSelfOwner: false,
    allowOwnerManagerChain: false,
    allowUnitManagerHierarchy: true,
    minimumRoleRankForUnitHierarchy: 4,
    allowResearchCustomers: false,
    additionalViewerRoleRanks: [],
  },
  {
    reportType: "ANALYTIC",
    allowSelfOwner: false,
    allowOwnerManagerChain: false,
    allowUnitManagerHierarchy: false,
    minimumRoleRankForUnitHierarchy: 1,
    allowResearchCustomers: true,
    additionalViewerRoleRanks: [],
  },
];

const now = new Date().toISOString();

export const seedReports: Report[] = [
  // === Процедура 1: Оценка лидерских компетенций (Hogan) ===
  {
    id: "report-individual-1",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "INDIVIDUAL",
    title: "Индивидуальный отчет Hogan HPI — Сотрудник отдела оценки персонала",
    filePath: "/uploads/mock-individual-u-employee.pdf",
    ownerUserId: "u-employee",
    unitId: "unit-assessment",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-individual-2",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "INDIVIDUAL",
    title: "Индивидуальный отчет Hogan HPI — Начальник отдела",
    filePath: "/uploads/mock-individual-u-head-section.pdf",
    ownerUserId: "u-head-section",
    unitId: "unit-assessment",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-individual-3",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "INDIVIDUAL",
    title: "Индивидуальный отчет Hogan HPI — Заказчик исследования",
    filePath: "/uploads/mock-individual-u-customer.pdf",
    ownerUserId: "u-customer",
    unitId: "unit-directorate",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-group-1",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "GROUP",
    title: "Групповой отчет Hogan — Отдел оценки персонала",
    filePath: "/uploads/mock-group-unit-assessment.pdf",
    ownerUserId: null,
    unitId: "unit-assessment",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-group-2",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "GROUP",
    title: "Групповой отчет Hogan — Управление",
    filePath: "/uploads/mock-group-unit-directorate.pdf",
    ownerUserId: null,
    unitId: "unit-directorate",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-summary-1",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "SUMMARY",
    title: "Сводный отчет Hogan — Управление",
    filePath: "/uploads/mock-summary-unit-directorate.pdf",
    ownerUserId: null,
    unitId: "unit-directorate",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-overall-1",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "OVERALL",
    title: "Общий отчет Hogan — Департамент",
    filePath: "/uploads/mock-overall-unit-department.pdf",
    ownerUserId: null,
    unitId: "unit-department",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-analytic-1",
    providerId: "provider-1",
    procedureId: "1",
    procedureName: "Оценка лидерских компетенций",
    type: "ANALYTIC",
    title: "Аналитический отчет Hogan — Кросс-функциональные команды",
    filePath: "/uploads/mock-analytic-cross-functional.pdf",
    ownerUserId: null,
    unitId: "unit-department",
    uploadedAt: now,
    customViewerUserIds: ["u-customer"],
  },

  // === Процедура 2: Оценка когнитивного потенциала (SHL) ===
  {
    id: "report-individual-shl-1",
    providerId: "provider-2",
    procedureId: "2",
    procedureName: "Оценка когнитивного потенциала",
    type: "INDIVIDUAL",
    title: "Индивидуальный отчет SHL OPQ — Сотрудник отдела оценки персонала",
    filePath: "/uploads/mock-shl-individual-u-employee.pdf",
    ownerUserId: "u-employee",
    unitId: "unit-assessment",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-individual-shl-2",
    providerId: "provider-2",
    procedureId: "2",
    procedureName: "Оценка когнитивного потенциала",
    type: "INDIVIDUAL",
    title: "Индивидуальный отчет SHL OPQ — Начальник отдела",
    filePath: "/uploads/mock-shl-individual-u-head-section.pdf",
    ownerUserId: "u-head-section",
    unitId: "unit-assessment",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-group-shl-1",
    providerId: "provider-2",
    procedureId: "2",
    procedureName: "Оценка когнитивного потенциала",
    type: "GROUP",
    title: "Групповой отчет SHL — Отдел оценки персонала",
    filePath: "/uploads/mock-shl-group-unit-assessment.pdf",
    ownerUserId: null,
    unitId: "unit-assessment",
    uploadedAt: now,
    customViewerUserIds: [],
  },
  {
    id: "report-summary-shl-1",
    providerId: "provider-2",
    procedureId: "2",
    procedureName: "Оценка когнитивного потенциала",
    type: "SUMMARY",
    title: "Сводный отчет SHL — Управление",
    filePath: "/uploads/mock-shl-summary-unit-directorate.pdf",
    ownerUserId: null,
    unitId: "unit-directorate",
    uploadedAt: now,
    customViewerUserIds: [],
  },
];
