import type { KPI, Stream } from "@/types/goals-kold";

// Моковые данные для годовых целей стрима
export const mockStreamKPIs: Record<string, Record<string, KPI[]>> = {
  "stream-1": {
    "2025": [
    {
      id: "kpi-1-1",
      number: 1,
      name: "Количество выпущенных релизов",
      weight: 25,
      type: "Количественный",
      unit: "шт.",
      plan: 12,
      fact: 10,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 83.3,
      evaluationPercent: 20.8,
    },
    {
      id: "kpi-1-2",
      number: 2,
      name: "Время разработки фичи",
      weight: 20,
      type: "Количественный",
      unit: "дн.",
      plan: 5,
      fact: 4.5,
      planStatus: "План выставление",
      factStatus: "Факт выставление",
      completionPercent: 111.1,
      evaluationPercent: 22.2,
    },
    {
      id: "kpi-1-3",
      number: 3,
      name: "Качество кода",
      weight: 20,
      type: "Качественный",
      unit: "%",
      plan: 85,
      fact: 88,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 103.5,
      evaluationPercent: 20.7,
    },
    {
      id: "kpi-1-4",
      number: 4,
      name: "Количество закрытых задач",
      weight: 20,
      type: "Количественный",
      unit: "шт.",
      plan: 500,
      fact: 480,
      planStatus: "План выставление",
      factStatus: "Факт согласован",
      completionPercent: 96,
      evaluationPercent: 19.2,
    },
    {
      id: "kpi-1-5",
      number: 5,
      name: "Удовлетворенность команды",
      weight: 15,
      type: "Качественный",
      unit: "%",
      plan: 80,
      fact: 82,
      planStatus: "План согласован",
      factStatus: "Факт выставление",
      completionPercent: 102.5,
      evaluationPercent: 15.4,
    },
  ],
    "2026": [],
  },
  "stream-2": {
    "2025": [
    {
      id: "kpi-2-1",
      number: 1,
      name: "Покрытие тестами",
      weight: 30,
      type: "Количественный",
      unit: "%",
      plan: 80,
      fact: 85,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 106.3,
      evaluationPercent: 31.9,
    },
    {
      id: "kpi-2-2",
      number: 2,
      name: "Количество найденных багов",
      weight: 25,
      type: "Количественный",
      unit: "шт.",
      plan: 50,
      fact: 45,
      planStatus: "План выставление",
      factStatus: "Факт согласован",
      completionPercent: 111.1,
      evaluationPercent: 27.8,
    },
    {
      id: "kpi-2-3",
      number: 3,
      name: "Время исправления критических багов",
      weight: 20,
      type: "Количественный",
      unit: "час.",
      plan: 4,
      fact: 3.5,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 114.3,
      evaluationPercent: 22.9,
    },
    {
      id: "kpi-2-4",
      number: 4,
      name: "Процент успешных тестов",
      weight: 15,
      type: "Количественный",
      unit: "%",
      plan: 95,
      fact: 97,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 102.1,
      evaluationPercent: 15.3,
    },
    {
      id: "kpi-2-5",
      number: 5,
      name: "Качество документации",
      weight: 10,
      type: "Качественный",
      unit: "%",
      plan: 75,
      fact: 78,
      planStatus: "План выставление",
      factStatus: "Факт согласован",
      completionPercent: 104,
      evaluationPercent: 10.4,
    },
  ],
    "2026": [],
  },
  "stream-3": {
    "2025": [
    {
      id: "kpi-3-1",
      number: 1,
      name: "Время развертывания",
      weight: 30,
      type: "Количественный",
      unit: "мин.",
      plan: 10,
      fact: 8,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 125,
      evaluationPercent: 37.5,
    },
    {
      id: "kpi-3-2",
      number: 2,
      name: "Доступность сервисов",
      weight: 25,
      type: "Количественный",
      unit: "%",
      plan: 99.9,
      fact: 99.95,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 100.1,
      evaluationPercent: 25,
    },
    {
      id: "kpi-3-3",
      number: 3,
      name: "Количество инцидентов",
      weight: 20,
      type: "Количественный",
      unit: "шт.",
      plan: 5,
      fact: 4,
      planStatus: "План выставление",
      factStatus: "Факт согласован",
      completionPercent: 125,
      evaluationPercent: 25,
    },
    {
      id: "kpi-3-4",
      number: 4,
      name: "Время восстановления сервиса",
      weight: 15,
      type: "Количественный",
      unit: "мин.",
      plan: 30,
      fact: 25,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 120,
      evaluationPercent: 18,
    },
    {
      id: "kpi-3-5",
      number: 5,
      name: "Эффективность использования ресурсов",
      weight: 10,
      type: "Количественный",
      unit: "%",
      plan: 85,
      fact: 88,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 103.5,
      evaluationPercent: 10.4,
    },
  ],
    "2026": [],
  },
  "stream-4": {
    "2025": [
    {
      id: "kpi-4-1",
      number: 1,
      name: "Количество обработанных неплатежей",
      weight: 30,
      type: "Количественный",
      unit: "шт.",
      plan: 1000,
      fact: 950,
      planStatus: "План выставление",
      factStatus: "Факт выставление",
      completionPercent: 95,
      evaluationPercent: 28.5,
    },
    {
      id: "kpi-4-2",
      number: 2,
      name: "Время обработки неплатежа",
      weight: 25,
      type: "Количественный",
      unit: "час.",
      plan: 2,
      fact: 1.8,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 111.1,
      evaluationPercent: 27.8,
    },
    {
      id: "kpi-4-3",
      number: 3,
      name: "Удовлетворенность клиентов",
      weight: 20,
      type: "Качественный",
      unit: "%",
      plan: 90,
      fact: 92,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 102.2,
      evaluationPercent: 20.4,
    },
    {
      id: "kpi-4-4",
      number: 4,
      name: "Количество обработанных непереводов",
      weight: 15,
      type: "Количественный",
      unit: "шт.",
      plan: 800,
      fact: 780,
      planStatus: "План выставление",
      factStatus: "Факт выставление",
      completionPercent: 97.5,
      evaluationPercent: 14.6,
    },
    {
      id: "kpi-4-5",
      number: 5,
      name: "Точность обработки",
      weight: 10,
      type: "Качественный",
      unit: "%",
      plan: 98,
      fact: 98.5,
      planStatus: "План согласован",
      factStatus: "Факт согласован",
      completionPercent: 100.5,
      evaluationPercent: 10.1,
    },
  ],
    "2026": [],
  },
};

// Моковые данные для квартальных КПЭ
export const mockQuarterlyKPIsData: Record<string, Record<string, KPI[]>> = {
  "stream-1": {
    "q1-2025": [
      {
        id: "q1-kpi-1-1",
        number: 1,
        name: "Количество выпущенных релизов",
        weight: 25,
        type: "Количественный",
        unit: "шт.",
        plan: 3,
        fact: 2,
        planStatus: "План выставление",
        factStatus: "Факт выставление",
        completionPercent: 66.7,
        evaluationPercent: 16.7,
        jiraTasks: [
          {
            id: "jira-task-1",
            key: "PROJ-123",
            summary: "Подготовка релиза v1.2.0",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Иванов И.И.",
            issueType: "Task",
            priority: "High",
            dueDate: "2025-03-15",
            createdDate: "2025-01-10",
            updatedDate: "2025-02-20",
            url: "https://jira.example.com/browse/PROJ-123",
            kpiIds: ["q1-kpi-1-1"],
          },
          {
            id: "jira-task-2",
            key: "PROJ-145",
            summary: "Тестирование релиза v1.2.0",
            status: "To Do",
            statusColor: "#42526E",
            assignee: "Петрова М.С.",
            issueType: "Task",
            priority: "Medium",
            dueDate: "2025-03-20",
            createdDate: "2025-01-15",
            updatedDate: "2025-02-18",
            url: "https://jira.example.com/browse/PROJ-145",
            kpiIds: ["q1-kpi-1-1"],
          },
        ],
      },
      {
        id: "q1-kpi-1-2",
        number: 2,
        name: "Время разработки фичи",
        weight: 20,
        type: "Количественный",
        unit: "дн.",
        plan: 5,
        fact: 4.8,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 104.2,
        evaluationPercent: 20.8,
        jiraTasks: [
          {
            id: "jira-task-3",
            key: "PROJ-167",
            summary: "Разработка новой функции авторизации",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Сидоров П.А.",
            issueType: "Story",
            priority: "High",
            dueDate: "2025-02-28",
            createdDate: "2025-01-05",
            updatedDate: "2025-02-25",
            url: "https://jira.example.com/browse/PROJ-167",
            kpiIds: ["q1-kpi-1-2"],
          },
          {
            id: "jira-task-4",
            key: "PROJ-189",
            summary: "Оптимизация времени загрузки страницы",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Козлова А.В.",
            issueType: "Task",
            priority: "Medium",
            dueDate: "2025-03-10",
            createdDate: "2025-01-20",
            updatedDate: "2025-02-22",
            url: "https://jira.example.com/browse/PROJ-189",
            kpiIds: ["q1-kpi-1-2"],
          },
        ],
      },
      {
        id: "q1-kpi-1-3",
        number: 3,
        name: "Качество кода",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 85,
        fact: 87,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 102.4,
        evaluationPercent: 20.5,
      },
      {
        id: "q1-kpi-1-4",
        number: 4,
        name: "Количество закрытых задач",
        weight: 20,
        type: "Количественный",
        unit: "шт.",
        plan: 125,
        fact: 120,
        planStatus: "План выставление",
        factStatus: "Факт выставление",
        completionPercent: 96,
        evaluationPercent: 19.2,
        jiraTasks: [
          {
            id: "jira-task-5",
            key: "PROJ-201",
            summary: "Исправление бага в модуле платежей",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Иванов И.И.",
            issueType: "Bug",
            priority: "Critical",
            dueDate: "2025-02-15",
            createdDate: "2025-01-12",
            updatedDate: "2025-02-14",
            url: "https://jira.example.com/browse/PROJ-201",
            kpiIds: ["q1-kpi-1-4"],
          },
          {
            id: "jira-task-6",
            key: "PROJ-215",
            summary: "Рефакторинг кода модуля отчетности",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Петрова М.С.",
            issueType: "Task",
            priority: "Low",
            dueDate: "2025-03-01",
            createdDate: "2025-01-18",
            updatedDate: "2025-02-28",
            url: "https://jira.example.com/browse/PROJ-215",
            kpiIds: ["q1-kpi-1-4"],
          },
          {
            id: "jira-task-7",
            key: "PROJ-228",
            summary: "Добавление новых тестов для API",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Сидоров П.А.",
            issueType: "Task",
            priority: "Medium",
            dueDate: "2025-03-05",
            createdDate: "2025-01-25",
            updatedDate: "2025-02-23",
            url: "https://jira.example.com/browse/PROJ-228",
            kpiIds: ["q1-kpi-1-4"],
          },
        ],
      },
      {
        id: "q1-kpi-1-5",
        number: 5,
        name: "Удовлетворенность команды",
        weight: 15,
        type: "Качественный",
        unit: "%",
        plan: 80,
        fact: 81,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 101.3,
        evaluationPercent: 15.2,
      },
    ],
    "q2-2025": [
      {
        id: "q2-kpi-1-1",
        number: 1,
        name: "Количество выпущенных релизов",
        weight: 25,
        type: "Количественный",
        unit: "шт.",
        plan: 3,
        fact: 3,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100,
        evaluationPercent: 25,
      },
      {
        id: "q2-kpi-1-2",
        number: 2,
        name: "Время разработки фичи",
        weight: 20,
        type: "Количественный",
        unit: "дн.",
        plan: 5,
        fact: 4.5,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 111.1,
        evaluationPercent: 22.2,
      },
      {
        id: "q2-kpi-1-3",
        number: 3,
        name: "Качество кода",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 85,
        fact: 88,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 103.5,
        evaluationPercent: 20.7,
      },
      {
        id: "q2-kpi-1-4",
        number: 4,
        name: "Количество закрытых задач",
        weight: 20,
        type: "Количественный",
        unit: "шт.",
        plan: 125,
        fact: 130,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 104,
        evaluationPercent: 20.8,
      },
      {
        id: "q2-kpi-1-5",
        number: 5,
        name: "Удовлетворенность команды",
        weight: 15,
        type: "Качественный",
        unit: "%",
        plan: 80,
        fact: 82,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 102.5,
        evaluationPercent: 15.4,
      },
    ],
    "q3-2025": [
      {
        id: "q3-kpi-1-1",
        number: 1,
        name: "Количество выпущенных релизов",
        weight: 25,
        type: "Количественный",
        unit: "шт.",
        plan: 3,
        fact: 3,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100,
        evaluationPercent: 25,
      },
      {
        id: "q3-kpi-1-2",
        number: 2,
        name: "Время разработки фичи",
        weight: 20,
        type: "Количественный",
        unit: "дн.",
        plan: 5,
        fact: 4.2,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 119,
        evaluationPercent: 23.8,
      },
      {
        id: "q3-kpi-1-3",
        number: 3,
        name: "Качество кода",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 85,
        fact: 89,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 104.7,
        evaluationPercent: 20.9,
      },
      {
        id: "q3-kpi-1-4",
        number: 4,
        name: "Количество закрытых задач",
        weight: 20,
        type: "Количественный",
        unit: "шт.",
        plan: 125,
        fact: 125,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100,
        evaluationPercent: 20,
      },
      {
        id: "q3-kpi-1-5",
        number: 5,
        name: "Удовлетворенность команды",
        weight: 15,
        type: "Качественный",
        unit: "%",
        plan: 80,
        fact: 83,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 103.8,
        evaluationPercent: 15.6,
      },
    ],
    "q4-2025": [
      {
        id: "q4-kpi-1-1",
        number: 1,
        name: "Количество выпущенных релизов",
        weight: 25,
        type: "Количественный",
        unit: "шт.",
        plan: 3,
        fact: 2,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 66.7,
        evaluationPercent: 16.7,
      },
      {
        id: "q4-kpi-1-2",
        number: 2,
        name: "Время разработки фичи",
        weight: 20,
        type: "Количественный",
        unit: "дн.",
        plan: 5,
        fact: 4.5,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 111.1,
        evaluationPercent: 22.2,
      },
      {
        id: "q4-kpi-1-3",
        number: 3,
        name: "Качество кода",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 85,
        fact: 88,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 103.5,
        evaluationPercent: 20.7,
      },
      {
        id: "q4-kpi-1-4",
        number: 4,
        name: "Количество закрытых задач",
        weight: 20,
        type: "Количественный",
        unit: "шт.",
        plan: 125,
        fact: 115,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 92,
        evaluationPercent: 18.4,
      },
      {
        id: "q4-kpi-1-5",
        number: 5,
        name: "Удовлетворенность команды",
        weight: 15,
        type: "Качественный",
        unit: "%",
        plan: 80,
        fact: 82,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 102.5,
        evaluationPercent: 15.4,
      },
    ],
  },
  "stream-4": {
    "q1-2025": [
      {
        id: "q1-kpi-4-1",
        number: 1,
        name: "Количество обработанных неплатежей",
        weight: 30,
        type: "Количественный",
        unit: "шт.",
        plan: 250,
        fact: 240,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 96,
        evaluationPercent: 28.8,
        jiraTasks: [
          {
            id: "jira-task-np-1",
            key: "NP-101",
            summary: "Автоматизация обработки неплатежей по картам",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Смирнов А.В.",
            issueType: "Story",
            priority: "High",
            dueDate: "2025-03-20",
            createdDate: "2025-01-05",
            updatedDate: "2025-02-18",
            url: "https://jira.example.com/browse/NP-101",
            kpiIds: ["q1-kpi-4-1"],
          },
          {
            id: "jira-task-np-2",
            key: "NP-115",
            summary: "Интеграция с системой уведомлений о неплатежах",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Кузнецова Е.П.",
            issueType: "Task",
            priority: "Medium",
            dueDate: "2025-02-28",
            createdDate: "2025-01-10",
            updatedDate: "2025-02-25",
            url: "https://jira.example.com/browse/NP-115",
            kpiIds: ["q1-kpi-4-1"],
          },
          {
            id: "jira-task-np-3",
            key: "NP-128",
            summary: "Оптимизация процесса обработки массовых неплатежей",
            status: "To Do",
            statusColor: "#42526E",
            assignee: "Петров Д.С.",
            issueType: "Task",
            priority: "High",
            dueDate: "2025-03-25",
            createdDate: "2025-01-15",
            updatedDate: "2025-02-20",
            url: "https://jira.example.com/browse/NP-128",
            kpiIds: ["q1-kpi-4-1"],
          },
        ],
      },
      {
        id: "q1-kpi-4-2",
        number: 2,
        name: "Время обработки неплатежа",
        weight: 25,
        type: "Количественный",
        unit: "час.",
        plan: 2,
        fact: 1.9,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 105.3,
        evaluationPercent: 26.3,
        jiraTasks: [
          {
            id: "jira-task-np-4",
            key: "NP-142",
            summary: "Внедрение системы приоритизации неплатежей",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Иванова М.А.",
            issueType: "Story",
            priority: "Critical",
            dueDate: "2025-03-15",
            createdDate: "2025-01-08",
            updatedDate: "2025-02-22",
            url: "https://jira.example.com/browse/NP-142",
            kpiIds: ["q1-kpi-4-2"],
          },
          {
            id: "jira-task-np-5",
            key: "NP-156",
            summary: "Улучшение алгоритма автоматической классификации неплатежей",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Соколов В.И.",
            issueType: "Task",
            priority: "High",
            dueDate: "2025-02-20",
            createdDate: "2025-01-12",
            updatedDate: "2025-02-18",
            url: "https://jira.example.com/browse/NP-156",
            kpiIds: ["q1-kpi-4-2"],
          },
        ],
      },
      {
        id: "q1-kpi-4-3",
        number: 3,
        name: "Удовлетворенность клиентов",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 90,
        fact: 91,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 101.1,
        evaluationPercent: 20.2,
      },
      {
        id: "q1-kpi-4-4",
        number: 4,
        name: "Количество обработанных непереводов",
        weight: 15,
        type: "Количественный",
        unit: "шт.",
        plan: 200,
        fact: 195,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 97.5,
        evaluationPercent: 14.6,
        jiraTasks: [
          {
            id: "jira-task-np-6",
            key: "NP-201",
            summary: "Разработка модуля обработки непереводов между счетами",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Волкова О.Н.",
            issueType: "Story",
            priority: "High",
            dueDate: "2025-03-18",
            createdDate: "2025-01-10",
            updatedDate: "2025-02-21",
            url: "https://jira.example.com/browse/NP-201",
            kpiIds: ["q1-kpi-4-4"],
          },
          {
            id: "jira-task-np-7",
            key: "NP-218",
            summary: "Автоматизация уведомлений клиентов о непереводах",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Морозов И.П.",
            issueType: "Task",
            priority: "Medium",
            dueDate: "2025-02-25",
            createdDate: "2025-01-15",
            updatedDate: "2025-02-23",
            url: "https://jira.example.com/browse/NP-218",
            kpiIds: ["q1-kpi-4-4"],
          },
          {
            id: "jira-task-np-8",
            key: "NP-234",
            summary: "Исправление бага с обработкой непереводов в выходные дни",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Лебедева А.С.",
            issueType: "Bug",
            priority: "Critical",
            dueDate: "2025-02-10",
            createdDate: "2025-01-20",
            updatedDate: "2025-02-08",
            url: "https://jira.example.com/browse/NP-234",
            kpiIds: ["q1-kpi-4-4"],
          },
        ],
      },
      {
        id: "q1-kpi-4-5",
        number: 5,
        name: "Точность обработки",
        weight: 10,
        type: "Качественный",
        unit: "%",
        plan: 98,
        fact: 98.2,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100.2,
        evaluationPercent: 10,
      },
    ],
    "q2-2025": [
      {
        id: "q2-kpi-4-1",
        number: 1,
        name: "Количество обработанных неплатежей",
        weight: 30,
        type: "Количественный",
        unit: "шт.",
        plan: 250,
        fact: 250,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100,
        evaluationPercent: 30,
        jiraTasks: [
          {
            id: "jira-task-np-9",
            key: "NP-301",
            summary: "Масштабирование системы обработки неплатежей",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Смирнов А.В.",
            issueType: "Story",
            priority: "High",
            dueDate: "2025-05-30",
            createdDate: "2025-04-01",
            updatedDate: "2025-05-28",
            url: "https://jira.example.com/browse/NP-301",
            kpiIds: ["q2-kpi-4-1"],
          },
          {
            id: "jira-task-np-10",
            key: "NP-315",
            summary: "Внедрение машинного обучения для прогнозирования неплатежей",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Кузнецова Е.П.",
            issueType: "Epic",
            priority: "High",
            dueDate: "2025-06-15",
            createdDate: "2025-04-05",
            updatedDate: "2025-05-20",
            url: "https://jira.example.com/browse/NP-315",
            kpiIds: ["q2-kpi-4-1"],
          },
        ],
      },
      {
        id: "q2-kpi-4-2",
        number: 2,
        name: "Время обработки неплатежа",
        weight: 25,
        type: "Количественный",
        unit: "час.",
        plan: 2,
        fact: 1.8,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 111.1,
        evaluationPercent: 27.8,
      },
      {
        id: "q2-kpi-4-3",
        number: 3,
        name: "Удовлетворенность клиентов",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 90,
        fact: 92,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 102.2,
        evaluationPercent: 20.4,
      },
      {
        id: "q2-kpi-4-4",
        number: 4,
        name: "Количество обработанных непереводов",
        weight: 15,
        type: "Количественный",
        unit: "шт.",
        plan: 200,
        fact: 200,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100,
        evaluationPercent: 15,
        jiraTasks: [
          {
            id: "jira-task-np-11",
            key: "NP-401",
            summary: "Оптимизация процесса обработки непереводов в реальном времени",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Волкова О.Н.",
            issueType: "Story",
            priority: "Medium",
            dueDate: "2025-05-25",
            createdDate: "2025-04-03",
            updatedDate: "2025-05-23",
            url: "https://jira.example.com/browse/NP-401",
            kpiIds: ["q2-kpi-4-4"],
          },
          {
            id: "jira-task-np-12",
            key: "NP-418",
            summary: "Интеграция с внешними системами для отслеживания непереводов",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Морозов И.П.",
            issueType: "Task",
            priority: "High",
            dueDate: "2025-06-10",
            createdDate: "2025-04-08",
            updatedDate: "2025-05-22",
            url: "https://jira.example.com/browse/NP-418",
            kpiIds: ["q2-kpi-4-4"],
          },
        ],
      },
      {
        id: "q2-kpi-4-5",
        number: 5,
        name: "Точность обработки",
        weight: 10,
        type: "Качественный",
        unit: "%",
        plan: 98,
        fact: 98.5,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100.5,
        evaluationPercent: 10.1,
      },
    ],
    "q3-2025": [
      {
        id: "q3-kpi-4-1",
        number: 1,
        name: "Количество обработанных неплатежей",
        weight: 30,
        type: "Количественный",
        unit: "шт.",
        plan: 250,
        fact: 230,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 92,
        evaluationPercent: 27.6,
        jiraTasks: [
          {
            id: "jira-task-np-13",
            key: "NP-501",
            summary: "Реализация дашборда для мониторинга неплатежей",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Петров Д.С.",
            issueType: "Story",
            priority: "Medium",
            dueDate: "2025-08-20",
            createdDate: "2025-07-01",
            updatedDate: "2025-08-18",
            url: "https://jira.example.com/browse/NP-501",
            kpiIds: ["q3-kpi-4-1"],
          },
          {
            id: "jira-task-np-14",
            key: "NP-515",
            summary: "Улучшение системы отчетности по неплатежам",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Иванова М.А.",
            issueType: "Task",
            priority: "Low",
            dueDate: "2025-09-05",
            createdDate: "2025-07-05",
            updatedDate: "2025-08-25",
            url: "https://jira.example.com/browse/NP-515",
            kpiIds: ["q3-kpi-4-1"],
          },
        ],
      },
      {
        id: "q3-kpi-4-2",
        number: 2,
        name: "Время обработки неплатежа",
        weight: 25,
        type: "Количественный",
        unit: "час.",
        plan: 2,
        fact: 1.7,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 117.6,
        evaluationPercent: 29.4,
      },
      {
        id: "q3-kpi-4-3",
        number: 3,
        name: "Удовлетворенность клиентов",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 90,
        fact: 93,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 103.3,
        evaluationPercent: 20.7,
      },
      {
        id: "q3-kpi-4-4",
        number: 4,
        name: "Количество обработанных непереводов",
        weight: 15,
        type: "Количественный",
        unit: "шт.",
        plan: 200,
        fact: 195,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 97.5,
        evaluationPercent: 14.6,
        jiraTasks: [
          {
            id: "jira-task-np-15",
            key: "NP-601",
            summary: "Автоматизация процесса эскалации непереводов",
            status: "Done",
            statusColor: "#00875A",
            assignee: "Лебедева А.С.",
            issueType: "Story",
            priority: "High",
            dueDate: "2025-08-25",
            createdDate: "2025-07-03",
            updatedDate: "2025-08-23",
            url: "https://jira.example.com/browse/NP-601",
            kpiIds: ["q3-kpi-4-4"],
          },
          {
            id: "jira-task-np-16",
            key: "NP-618",
            summary: "Разработка API для работы с непереводами",
            status: "In Progress",
            statusColor: "#0052CC",
            assignee: "Соколов В.И.",
            issueType: "Task",
            priority: "Medium",
            dueDate: "2025-09-10",
            createdDate: "2025-07-08",
            updatedDate: "2025-08-28",
            url: "https://jira.example.com/browse/NP-618",
            kpiIds: ["q3-kpi-4-4"],
          },
        ],
      },
      {
        id: "q3-kpi-4-5",
        number: 5,
        name: "Точность обработки",
        weight: 10,
        type: "Качественный",
        unit: "%",
        plan: 98,
        fact: 98.8,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100.8,
        evaluationPercent: 10.1,
      },
    ],
    "q4-2025": [
      {
        id: "q4-kpi-4-1",
        number: 1,
        name: "Количество обработанных неплатежей",
        weight: 30,
        type: "Количественный",
        unit: "шт.",
        plan: 250,
        fact: 230,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 92,
        evaluationPercent: 27.6,
      },
      {
        id: "q4-kpi-4-2",
        number: 2,
        name: "Время обработки неплатежа",
        weight: 25,
        type: "Количественный",
        unit: "час.",
        plan: 2,
        fact: 1.8,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 111.1,
        evaluationPercent: 27.8,
      },
      {
        id: "q4-kpi-4-3",
        number: 3,
        name: "Удовлетворенность клиентов",
        weight: 20,
        type: "Качественный",
        unit: "%",
        plan: 90,
        fact: 92,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 102.2,
        evaluationPercent: 20.4,
      },
      {
        id: "q4-kpi-4-4",
        number: 4,
        name: "Количество обработанных непереводов",
        weight: 15,
        type: "Количественный",
        unit: "шт.",
        plan: 200,
        fact: 190,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 95,
        evaluationPercent: 14.3,
      },
      {
        id: "q4-kpi-4-5",
        number: 5,
        name: "Точность обработки",
        weight: 10,
        type: "Качественный",
        unit: "%",
        plan: 98,
        fact: 98.5,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100.5,
        evaluationPercent: 10.1,
      },
    ],
  },
};

// Моковые данные для квартальных КПЭ ИТ лидера
export const mockITLeaderKPIsData: Record<string, Record<string, KPI[]>> = {
  "stream-1": {
    "q1-2025": [
      {
        id: "it-q1-kpi-1-1",
        number: 1,
        name: "Время отклика системы",
        weight: 30,
        type: "Количественный",
        unit: "мс",
        plan: 100,
        fact: 95,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 105.3,
        evaluationPercent: 31.6,
      },
      {
        id: "it-q1-kpi-1-2",
        number: 2,
        name: "Доступность инфраструктуры",
        weight: 25,
        type: "Количественный",
        unit: "%",
        plan: 99.5,
        fact: 99.7,
        planStatus: "План согласован",
        factStatus: "Факт согласован",
        completionPercent: 100.2,
        evaluationPercent: 25.1,
      },
    ],
    "q2-2025": [],
    "q3-2025": [],
    "q4-2025": [],
  },
};

// Функция для генерации моковых данных стримов и команд (20 стримов, 60 команд)
export const generateMockStreams = (): Stream[] => {
  const streamNames = [
    "Стрим разработки",
    "Стрим качества",
    "Стрим инфраструктуры",
    "Неплатежи и непереводы",
    "Стрим аналитики",
    "Стрим безопасности",
    "Стрим интеграций",
    "Стрим мобильных решений",
    "Стрим обработки данных",
    "Стрим клиентского опыта",
    "Стрим платежных решений",
    "Стрим корпоративных решений",
    "Стрим API и микросервисов",
    "Стрим автоматизации",
    "Стрим мониторинга",
    "Стрим тестирования",
    "Стрим документации",
    "Стрим обучения",
    "Стрим поддержки",
    "Стрим консалтинга",
  ];

  const streamTypes: Array<"продуктовый" | "канальный" | "сегментный" | "платформенный" | "сервисный"> = [
    "продуктовый", "сервисный", "платформенный", "канальный", "продуктовый",
    "сервисный", "платформенный", "продуктовый", "сегментный", "канальный",
    "продуктовый", "сегментный", "платформенный", "сервисный", "платформенный",
    "сервисный", "сервисный", "сервисный", "сервисный", "сервисный",
  ];

  const leaders = [
    "Орлов Максим Сергеевич", "Зайцева Оксана Дмитриевна", "Григорьев Андрей Валерьевич",
    "Помыткин Сергей Олегович", "Волков Дмитрий Александрович", "Новикова Елена Сергеевна",
    "Кузнецов Игорь Викторович", "Морозова Анна Дмитриевна", "Соколов Павел Олегович",
    "Лебедева Мария Игоревна", "Козлов Владимир Петрович", "Смирнова Ольга Николаевна",
    "Петров Алексей Владимирович", "Иванова Татьяна Сергеевна", "Медведев Юрий Александрович",
    "Федорова Наталья Викторовна", "Павлов Станислав Олегович", "Романова Юлия Дмитриевна",
    "Семенов Артем Игоревич", "Ткачева Екатерина Дмитриевна",
  ];

  const itLeaders = [
    "Романова Юлия Дмитриевна", "Комаров Станислав Викторович", "Ларина Марина Игоревна",
    "Козлова Анна Петровна", "Иванов Сергей Викторович", "Петрова Елена Александровна",
    "Сидоров Андрей Николаевич", "Ковалева Ирина Олеговна", "Михайлов Денис Сергеевич",
    "Фомина Людмила Игоревна", "Борисов Максим Дмитриевич", "Зайцева Ольга Петровна",
    "Волков Алексей Владимирович", "Морозова Светлана Николаевна", "Соколов Игорь Александрович",
    "Новикова Татьяна Викторовна", "Кузнецова Мария Олеговна", "Лебедев Павел Сергеевич",
    "Смирнов Юрий Игоревич", "Павлова Анна Дмитриевна",
  ];

  const teamLeaders = [
    "Иванов Иван Иванович", "Петров Петр Петрович", "Сидорова Сидора Сидоровна",
    "Козлов Козел Козлович", "Смирнов Сергей Сергеевич", "Волкова Мария Александровна",
    "Новиков Дмитрий Игоревич", "Петрова Анна Викторовна", "Морозов Алексей Владимирович",
    "Кузнецова Елена Сергеевна", "Лебедев Игорь Николаевич", "Соколова Ольга Олеговна",
    "Павлов Станислав Викторович", "Федорова Наталья Александровна", "Медведев Юрий Сергеевич",
    "Иванова Татьяна Игоревна", "Романова Юлия Дмитриевна", "Семенов Артем Дмитриевич",
    "Ткачева Екатерина Петровна", "Борисов Максим Владимирович", "Зайцева Ольга Николаевна",
    "Волков Алексей Олегович", "Морозова Светлана Викторовна", "Соколов Игорь Александрович",
    "Новикова Татьяна Сергеевна", "Кузнецова Мария Игоревна", "Лебедев Павел Дмитриевич",
    "Смирнов Юрий Петрович", "Павлова Анна Владимировна", "Фомина Людмила Николаевна",
    "Михайлов Денис Олегович", "Ковалева Ирина Викторовна", "Борисова Елена Александровна",
    "Зайцев Сергей Сергеевич", "Волкова Ирина Игоревна", "Морозов Денис Дмитриевич",
    "Соколова Ольга Петровна", "Павлов Станислав Владимирович", "Федорова Наталья Николаевна",
    "Медведева Елена Олегович", "Иванов Игорь Викторович", "Романова Татьяна Александровна",
    "Семенов Артем Сергеевич", "Ткачева Мария Игоревна", "Борисов Максим Дмитриевич",
    "Зайцева Ольга Петровна", "Волков Алексей Владимирович", "Морозова Светлана Николаевна",
    "Соколов Игорь Олегович", "Новикова Татьяна Викторовна", "Кузнецова Елена Александровна",
    "Лебедев Павел Сергеевич", "Смирнов Юрий Игоревич", "Павлова Анна Дмитриевна",
    "Фомина Людмила Петровна", "Михайлов Денис Владимирович", "Ковалева Ирина Николаевна",
    "Борисова Елена Олегович", "Зайцев Сергей Викторович", "Волкова Ирина Александровна",
    "Морозов Денис Сергеевич", "Соколова Ольга Игоревна",
  ];

  const teamNames = [
    "Команда Frontend", "Команда Backend", "Команда QA", "Команда DevOps",
    "Команда обработки неплатежей", "Команда обработки непереводов", "Команда аналитики",
    "Команда поддержки клиентов", "Команда разработки API", "Команда мобильной разработки",
    "Команда тестирования", "Команда автоматизации", "Команда безопасности", "Команда мониторинга",
    "Команда документации", "Команда интеграций", "Команда обработки данных", "Команда клиентского опыта",
    "Команда платежных решений", "Команда корпоративных решений", "Команда микросервисов", "Команда обучения",
    "Команда поддержки", "Команда консалтинга", "Команда UX/UI", "Команда архитектуры",
    "Команда производительности", "Команда миграций", "Команда резервного копирования", "Команда развертывания",
    "Команда управления конфигурацией", "Команда управления рисками", "Команда комплаенса", "Команда аудита",
    "Команда отчетности", "Команда визуализации", "Команда машинного обучения", "Команда больших данных",
    "Команда облачных решений", "Команда контейнеризации", "Команда оркестрации", "Команда сервис-меша",
    "Команда событийной архитектуры", "Команда базы данных", "Команда кэширования", "Команда поиска",
    "Команда очередей", "Команда стриминга", "Команда репликации", "Команда балансировки",
    "Команда масштабирования", "Команда оптимизации", "Команда настройки", "Команда тюнинга",
    "Команда профилирования", "Команда отладки", "Команда логирования", "Команда трейсинга",
    "Команда метрик", "Команда алертинга", "Команда оповещений",
  ];

  // Распределение команд: 5 стримов по 4, 10 стримов по 3, 5 стримов по 2 = 60 команд
  const teamsPerStream = [4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2];
  const startDates = [
    "2024-01-15", "2024-02-01", "2024-03-10", "2024-01-20", "2024-04-05",
    "2024-02-15", "2024-03-25", "2024-04-10", "2024-05-01", "2024-01-10",
    "2024-02-20", "2024-03-05", "2024-04-15", "2024-05-10", "2024-01-25",
    "2024-02-10", "2024-03-20", "2024-04-01", "2024-05-15", "2024-01-30",
  ];

  const businessTypes: Array<"РБ" | "МСБ"> = ["РБ", "МСБ"];

  const streams: Stream[] = [];
  let teamCounter = 1;

  for (let i = 0; i < 20; i++) {
    const streamId = `stream-${i + 1}`;
    const streamName = streamNames[i];
    const numTeams = teamsPerStream[i];
    const teams = [];

    for (let j = 0; j < numTeams; j++) {
      teams.push({
        id: `team-${teamCounter}`,
        name: teamNames[teamCounter - 1] || `Команда ${teamCounter}`,
        description: `Описание команды ${teamCounter}`,
        streamId,
        streamName,
        leader: teamLeaders[(teamCounter - 1) % teamLeaders.length],
        membersCount: ((teamCounter - 1) % 10) + 5,
      });
      teamCounter++;
    }

    streams.push({
      id: streamId,
      name: streamName,
      description: `Описание стрима ${i + 1}`,
      type: streamTypes[i],
      businessType: businessTypes[i % 2],
      startDate: startDates[i],
      endDate: "2025-12-31",
      leader: {
        name: leaders[i],
        position: i % 2 === 0 ? "Исполнительный директор" : "Управляющий директор",
      },
      itLeader: {
        name: itLeaders[i],
        position: i % 2 === 0 ? "Управляющий директор" : "Исполнительный директор",
      },
      teams,
    });
  }

  return streams;
};

// Моковые данные стримов и команд (20 стримов, 60 команд)
export const mockStreams: Stream[] = generateMockStreams();

